#!/bin/bash
_uso() {
	echo "Uso: $0 <dirname> <num_files> <basefilename>"
}
_esdir() {
	local d=$1
	[ -d $d ] && return 0 || return 1
}
if [ $# -eq 3 ]; then
	if [ $2 -gt 0 ] && [ $2 -lt 100 ]; then
		if ! ( _esdir $1 ); then
			mkdir -p $1
			chmod u+rw $1
		fi
		for x in `seq -w 1 $2`; do
			touch $1/"$3$x"
		done
		echo -e "Se han creado todos los archivos en $1.\n"
		echo -e "Compruebelo usted mismo:\n"
		ls -l $1
	else
		echo "No has introducido un numero correcto de archivos."	
	fi
else
	_uso
fi
